### ISSUE TITLE
It will throw an exception when the collection is not found.

### ISSUE THREAD

**Issue by kyob1010** [TDLive/DSTServerModSetup#2]
Error log：
if( $(".breadcrumbs").children("a")[0].children[0].data != "Don't Starve Together" ) return reject(res, "item not for Don't Starve Together");
TypeError: Cannot read property 'children' of undefined

It can cause the system unworking.

**Comment by antigravities** [comment]
Thanks for the report, fixed in 419c4701d9f6cf0bd709541ca7d1762d2fe5f345.
